module.exports = {
  metaFilesLocation: 'testbed/meta',
  mediaFilesLocation: 'testbed/media',
  baseURL: 'https://smidgeo.com',
  rssFilename: 'test.xml',
  podcastImageURL: 'https://jimkang.com/smallfindings/media/small-findings.jpg',
  mediaBaseURL: 'https://smidgeo.com/notes/deathmtn/media',
  language: 'en',
  owner: 'Smidgeo',
  email: 'smidgeo@fastmail.com',
  category: 'Education',
  subcategory: 'Self-Improvement',
  explicit: 'No',
  subtitle: 'The audio posts from deathmtn notes.',
  summary: 'Sounds — verbal, musical, and otherwise — from everyday life.',
  author: 'deathmtn',
  podcastType: 'episodic',
  title: 'The podcast',
  description: 'The audio posts from the blog',
};
